# -*- coding: utf-8 -*-
"""Tugas Citra Histogram

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-nfhdPVTLsZ76dDDhJBKH1T00z93M4Kj

## Import Library
"""

import numpy as np
from google.colab import files
from PIL import Image
import matplotlib.pyplot as plt

"""## Upload Gambar"""

def upload_image():
    """Upload 1 gambar"""
    print("Silakan upload gambar:")
    uploaded = files.upload()
    filename = list(uploaded.keys())[0]
    return filename

def load_image(filename):
    """Load gambar dan konversi ke numpy array"""
    img = Image.open(filename)
    img_array = np.array(img)
    return img_array

"""## Fungsi Konversi RGB ke Grayscale"""

def rgb_to_grayscale_manual(img_rgb):
    """Konversi RGB ke Grayscale secara manual"""
    # Jika sudah grayscale, return langsung
    if len(img_rgb.shape) == 2:
        return img_rgb

    height, width = img_rgb.shape[0], img_rgb.shape[1]
    img_gray = np.zeros((height, width), dtype=np.uint8)

    # Proses setiap pixel secara manual
    for i in range(height):
        for j in range(width):
            r = img_rgb[i, j, 0]
            g = img_rgb[i, j, 1]
            b = img_rgb[i, j, 2]

            # Formula weighted average
            gray_value = int(0.299 * r + 0.587 * g + 0.114 * b)
            img_gray[i, j] = gray_value

    return img_gray

"""## Fungsi Hitung Histogram"""

def calculate_histogram_manual(img_gray):
    """
    Hitung histogram secara manual
    Returns: array dengan 256 elemen (intensitas 0-255)
    """
    # Inisialisasi histogram dengan 0
    histogram = np.zeros(256, dtype=int)

    height, width = img_gray.shape

    # Hitung frekuensi setiap intensitas pixel
    for i in range(height):
        for j in range(width):
            pixel_value = img_gray[i, j]
            histogram[pixel_value] += 1

    return histogram

"""## Fungsi Normalisasi Histogram"""

def normalize_histogram(histogram, total_pixels):
    """
    Normalisasi histogram menjadi probabilitas
    """
    histogram_normalized = np.zeros(256, dtype=float)

    for i in range(256):
        histogram_normalized[i] = histogram[i] / total_pixels

    return histogram_normalized

"""## Fungsi Analisis Kualitas Gambar"""

def analyze_image_quality(histogram, total_pixels):
    """Analisis kualitas gambar berdasarkan distribusi histogram"""

    # Hitung persentase pixel di setiap range
    dark_pixels = sum(histogram[0:85]) / total_pixels * 100
    mid_pixels = sum(histogram[85:170]) / total_pixels * 100
    bright_pixels = sum(histogram[170:256]) / total_pixels * 100

    # Hitung mean intensity
    mean_intensity = sum(i * histogram[i] for i in range(256)) / total_pixels

    # Tentukan kategori
    if dark_pixels > 60:
        category = "GELAP (Underexposed)"
        color = "darkblue"
    elif bright_pixels > 60:
        category = "TERANG (Overexposed)"
        color = "orange"
    else:
        category = "BAGUS (Well-exposed)"
        color = "green"

    return {
        'category': category,
        'color': color,
        'dark_percent': dark_pixels,
        'mid_percent': mid_pixels,
        'bright_percent': bright_pixels,
        'mean_intensity': mean_intensity
    }

print("  - GELAP: >60% pixel di intensitas 0-85")
print("  - TERANG: >60% pixel di intensitas 170-255")
print("  - BAGUS: Distribusi merata")

"""## Fungsi Tampilkan Histogram"""

def display_histogram(img_gray, histogram, histogram_norm, title, analysis):
    """Tampilkan gambar dengan histogram normal dan ternormalisasi"""

    fig = plt.figure(figsize=(16, 5))

    # Subplot 1: Gambar Grayscale
    ax1 = plt.subplot(1, 3, 1)
    ax1.imshow(img_gray, cmap='gray')
    ax1.set_title(f'{title}\n{analysis["category"]}',
                  fontsize=13, fontweight='bold', color=analysis['color'])
    ax1.axis('off')

    # Tambahkan info statistik
    textstr = f'Mean Intensity: {analysis["mean_intensity"]:.1f}\n'
    textstr += f'Dark (0-85): {analysis["dark_percent"]:.1f}%\n'
    textstr += f'Mid (85-170): {analysis["mid_percent"]:.1f}%\n'
    textstr += f'Bright (170-255): {analysis["bright_percent"]:.1f}%'

    props = dict(boxstyle='round', facecolor='wheat', alpha=0.85)
    ax1.text(0.02, 0.98, textstr, transform=ax1.transAxes, fontsize=10,
             verticalalignment='top', bbox=props)

    # Subplot 2: Histogram Normal
    ax2 = plt.subplot(1, 3, 2)
    ax2.bar(range(256), histogram, color='steelblue', width=1.0, edgecolor='none')
    ax2.set_title('Histogram Normal\n(Frekuensi Pixel)', fontsize=12, fontweight='bold')
    ax2.set_xlabel('Intensitas Pixel (0-255)', fontsize=10)
    ax2.set_ylabel('Frekuensi', fontsize=10)
    ax2.set_xlim([0, 255])
    ax2.grid(True, alpha=0.3, linestyle='--')

    # Subplot 3: Histogram Ternormalisasi
    ax3 = plt.subplot(1, 3, 3)
    ax3.bar(range(256), histogram_norm, color='coral', width=1.0, edgecolor='none')
    ax3.set_title('Histogram Ternormalisasi\n(Probabilitas)', fontsize=12, fontweight='bold')
    ax3.set_xlabel('Intensitas Pixel (0-255)', fontsize=10)
    ax3.set_ylabel('Probabilitas', fontsize=10)
    ax3.set_xlim([0, 255])
    ax3.set_ylim([0, max(histogram_norm) * 1.1])
    ax3.grid(True, alpha=0.3, linestyle='--')

    plt.tight_layout()
    plt.show()

"""## GAMBAR BAGUS - Upload"""

print("="*70)
print("GAMBAR 1: GAMBAR BAGUS (WELL-EXPOSED)")
print("="*70)
print("Upload gambar dengan pencahayaan yang baik")
print("Gambar dengan distribusi intensitas yang merata")
print("="*70)

filename_bagus = upload_image()
print(f"\n✓ File uploaded: {filename_bagus}")

"""## GAMBAR BAGUS - Proses dan Menampilkan Histogram"""

print("="*70)
print("MEMPROSES GAMBAR BAGUS")
print("="*70)

# Load gambar
img_bagus = load_image(filename_bagus)
print(f"✓ Gambar dimuat - Ukuran: {img_bagus.shape}")

# Konversi ke grayscale
print("Konversi ke grayscale...")
img_bagus_gray = rgb_to_grayscale_manual(img_bagus)
print(f"✓ Konversi selesai - Shape: {img_bagus_gray.shape}")

# Hitung histogram
print("Menghitung histogram...")
histogram_bagus = calculate_histogram_manual(img_bagus_gray)
total_pixels_bagus = img_bagus_gray.shape[0] * img_bagus_gray.shape[1]
print(f"✓ Total pixels: {total_pixels_bagus:,}")

# Normalisasi histogram
print("Normalisasi histogram...")
histogram_bagus_norm = normalize_histogram(histogram_bagus, total_pixels_bagus)
print(f"✓ Histogram ternormalisasi")

# Analisis kualitas
print("Analisis kualitas gambar...")
analysis_bagus = analyze_image_quality(histogram_bagus, total_pixels_bagus)
print(f"✓ Kategori: {analysis_bagus['category']}")

print("\n" + "="*70)
print("HASIL ANALISIS GAMBAR BAGUS")
print("="*70)
print(f"Kategori: {analysis_bagus['category']}")
print(f"Mean Intensity: {analysis_bagus['mean_intensity']:.2f}")
print(f"\nDistribusi Pixel:")
print(f"  - Dark (0-85):      {analysis_bagus['dark_percent']:.1f}%")
print(f"  - Mid (85-170):     {analysis_bagus['mid_percent']:.1f}%")
print(f"  - Bright (170-255): {analysis_bagus['bright_percent']:.1f}%")
print("="*70)

# Tampilkan histogram
print("\nMenampilkan histogram...\n")
display_histogram(img_bagus_gray, histogram_bagus, histogram_bagus_norm,
                  'Gambar Bagus', analysis_bagus)

"""## GAMBAR GELAP - Upload"""

print("="*70)
print("GAMBAR 2: GAMBAR GELAP (UNDEREXPOSED)")
print("="*70)
print("Upload gambar yang gelap/kurang cahaya")
print("Gambar dengan banyak pixel di intensitas rendah")
print("="*70)

filename_gelap = upload_image()
print(f"\n✓ File uploaded: {filename_gelap}")

"""## GAMBAR GELAP - Proses dan Menampilkan Histogram"""

print("="*70)
print("MEMPROSES GAMBAR GELAP")
print("="*70)

# Load gambar
img_gelap = load_image(filename_gelap)
print(f"✓ Gambar dimuat - Ukuran: {img_gelap.shape}")

# Konversi ke grayscale
print("Konversi ke grayscale...")
img_gelap_gray = rgb_to_grayscale_manual(img_gelap)
print(f"✓ Konversi selesai - Shape: {img_gelap_gray.shape}")

# Hitung histogram
print("Menghitung histogram...")
histogram_gelap = calculate_histogram_manual(img_gelap_gray)
total_pixels_gelap = img_gelap_gray.shape[0] * img_gelap_gray.shape[1]
print(f"✓ Total pixels: {total_pixels_gelap:,}")

# Normalisasi histogram
print("Normalisasi histogram...")
histogram_gelap_norm = normalize_histogram(histogram_gelap, total_pixels_gelap)
print(f"✓ Histogram ternormalisasi")

# Analisis kualitas
print("Analisis kualitas gambar...")
analysis_gelap = analyze_image_quality(histogram_gelap, total_pixels_gelap)
print(f"✓ Kategori: {analysis_gelap['category']}")

print("\n" + "="*70)
print("HASIL ANALISIS GAMBAR GELAP")
print("="*70)
print(f"Kategori: {analysis_gelap['category']}")
print(f"Mean Intensity: {analysis_gelap['mean_intensity']:.2f}")
print(f"\nDistribusi Pixel:")
print(f"  - Dark (0-85):      {analysis_gelap['dark_percent']:.1f}%")
print(f"  - Mid (85-170):     {analysis_gelap['mid_percent']:.1f}%")
print(f"  - Bright (170-255): {analysis_gelap['bright_percent']:.1f}%")
print("="*70)

# Tampilkan histogram
print("\nMenampilkan histogram...\n")
display_histogram(img_gelap_gray, histogram_gelap, histogram_gelap_norm,
                  'Gambar Gelap', analysis_gelap)

"""## GAMBAR TERANG - Upload"""

print("="*70)
print("GAMBAR 3: GAMBAR TERANG (OVEREXPOSED)")
print("="*70)
print("Upload gambar yang terlalu terang/overexposed")
print("Gambar dengan banyak pixel di intensitas tinggi")
print("="*70)

filename_terang = upload_image()
print(f"\n✓ File uploaded: {filename_terang}")

"""## GAMBAR TERANG - Proses dan Menampilkan Histogram"""

print("="*70)
print("MEMPROSES GAMBAR TERANG")
print("="*70)

# Load gambar
img_terang = load_image(filename_terang)
print(f"✓ Gambar dimuat - Ukuran: {img_terang.shape}")

# Konversi ke grayscale
print("Konversi ke grayscale...")
img_terang_gray = rgb_to_grayscale_manual(img_terang)
print(f"✓ Konversi selesai - Shape: {img_terang_gray.shape}")

# Hitung histogram
print("Menghitung histogram...")
histogram_terang = calculate_histogram_manual(img_terang_gray)
total_pixels_terang = img_terang_gray.shape[0] * img_terang_gray.shape[1]
print(f"✓ Total pixels: {total_pixels_terang:,}")

# Normalisasi histogram
print("Normalisasi histogram...")
histogram_terang_norm = normalize_histogram(histogram_terang, total_pixels_terang)
print(f"✓ Histogram ternormalisasi")

# Analisis kualitas
print("Analisis kualitas gambar...")
analysis_terang = analyze_image_quality(histogram_terang, total_pixels_terang)
print(f"✓ Kategori: {analysis_terang['category']}")

print("\n" + "="*70)
print("HASIL ANALISIS GAMBAR TERANG")
print("="*70)
print(f"Kategori: {analysis_terang['category']}")
print(f"Mean Intensity: {analysis_terang['mean_intensity']:.2f}")
print(f"\nDistribusi Pixel:")
print(f"  - Dark (0-85):      {analysis_terang['dark_percent']:.1f}%")
print(f"  - Mid (85-170):     {analysis_terang['mid_percent']:.1f}%")
print(f"  - Bright (170-255): {analysis_terang['bright_percent']:.1f}%")
print("="*70)

# Tampilkan histogram
print("\nMenampilkan histogram...\n")
display_histogram(img_terang_gray, histogram_terang, histogram_terang_norm,
                  'Gambar Terang', analysis_terang)

"""## PERBANDINGAN KETIGA GAMBAR"""

print("="*70)
print("PERBANDINGAN KETIGA GAMBAR")
print("="*70)

fig, axes = plt.subplots(3, 3, figsize=(16, 14))

# Data untuk 3 gambar
images_data = [
    {
        'gray': img_bagus_gray,
        'hist': histogram_bagus,
        'hist_norm': histogram_bagus_norm,
        'analysis': analysis_bagus,
        'title': 'Gambar Bagus'
    },
    {
        'gray': img_gelap_gray,
        'hist': histogram_gelap,
        'hist_norm': histogram_gelap_norm,
        'analysis': analysis_gelap,
        'title': 'Gambar Gelap'
    },
    {
        'gray': img_terang_gray,
        'hist': histogram_terang,
        'hist_norm': histogram_terang_norm,
        'analysis': analysis_terang,
        'title': 'Gambar Terang'
    }
]

for idx, data in enumerate(images_data):
    # Kolom 1: Gambar
    axes[idx, 0].imshow(data['gray'], cmap='gray')
    axes[idx, 0].set_title(f'{data["title"]}\n{data["analysis"]["category"]}',
                           fontsize=11, fontweight='bold',
                           color=data['analysis']['color'])
    axes[idx, 0].axis('off')

    # Kolom 2: Histogram Normal
    axes[idx, 1].bar(range(256), data['hist'], color='steelblue',
                     width=1.0, edgecolor='none')
    axes[idx, 1].set_title('Histogram Normal', fontsize=10, fontweight='bold')
    axes[idx, 1].set_xlabel('Intensitas (0-255)', fontsize=9)
    axes[idx, 1].set_ylabel('Frekuensi', fontsize=9)
    axes[idx, 1].set_xlim([0, 255])
    axes[idx, 1].grid(True, alpha=0.3, linestyle='--')

    # Kolom 3: Histogram Ternormalisasi
    axes[idx, 2].bar(range(256), data['hist_norm'], color='coral',
                     width=1.0, edgecolor='none')
    axes[idx, 2].set_title('Histogram Ternormalisasi', fontsize=10, fontweight='bold')
    axes[idx, 2].set_xlabel('Intensitas (0-255)', fontsize=9)
    axes[idx, 2].set_ylabel('Probabilitas', fontsize=9)
    axes[idx, 2].set_xlim([0, 255])
    axes[idx, 2].grid(True, alpha=0.3, linestyle='--')

plt.tight_layout()
plt.show()

# Tampilkan ringkasan
print("\n" + "="*70)
print("RINGKASAN ANALISIS KETIGA GAMBAR")
print("="*70)

for idx, data in enumerate(images_data, 1):
    analysis = data['analysis']
    print(f"\n{data['title']}:")
    print(f"  Kategori: {analysis['category']}")
    print(f"  Mean Intensity: {analysis['mean_intensity']:.2f}")
    print(f"  Distribusi:")
    print(f"    - Dark (0-85):      {analysis['dark_percent']:.1f}%")
    print(f"    - Mid (85-170):     {analysis['mid_percent']:.1f}%")
    print(f"    - Bright (170-255): {analysis['bright_percent']:.1f}%")

print("\n" + "="*70)